### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by wiggleforlife** [KSanders7070/Virtual_RADAR_Client_Workstation_Setup#1]
It'd be nice to be able to add custom URLs, edit paths and more through a file instead of the program. I'm imagining something like a .DESKTOP file on Linux, with this sort of syntax:
```
PROGRAM="C:\Program Files(x86)\vSTARS\vSTARS.exe"
URL="https://zlcartcc.net"
```
It would be nice if the `https://` could be removed, but obviously not a necessity.

**Comment by KSanders7070** [comment]
Look in your Documents folder/ATC Workstation Setup

**Comment by wiggleforlife** [comment]
I see that now. Seems a little unnecessary to have so many files with only one line though. Is it possible to merge them all?

**Comment by KSanders7070** [comment]
It is. This was my first coding project and therefore there is a great deal of things that need to be refactored, this is one of them. But, for it works and I'd rather just wait to convert the project into an application later on.
